language: java
sudo: required

jdk:
- openjdk11

install: true
script:
  - ./gradlew ci --stacktrace --no-daemon

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./misc/upload.sh
